volumes:
  happimo_dev_postgres_data: {}
  happimo_dev_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: happimo_dev
    container_name: happimo_dev_django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mailpit
      - memcached

  postgres:
    image: postgres:16.3-alpine3.20
    container_name: happimo_dev_postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - happimo_dev_postgres_data:/var/lib/postgresql/data
      - happimo_dev_postgres_data_backups:/backups

  memcached:
    image: memcached:1.6.28-alpine3.20
    container_name: happimo_dev_memcached
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit:v1.18
    container_name: happimo_dev_mailpit
    ports:
      - "8025:8025"
