# Generated by Django 5.0.6 on 2024-06-04 16:28

import moods.form_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_alter_activity_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=moods.form_fields.ColorField(default='#7542e6', max_length=8),
        ),
    ]
