from django.urls import path
from moods.views.entry_views import (
    EntryCreateView,
    EntryDeleteView,
    EntryUpdateView,
    EntryListView,
)
from moods.views.mood_views import (
    MoodCreateView,
    MoodDeleteView,
    MoodListView,
    MoodUpdateView,
    MoodReorderView,
)
from moods.views.activity_views import (
    ActivityCreateView,
    ActivityDeleteView,
    ActivityListView,
    ActivityUpdateView,
)

urlpatterns = [
    path(
        "",
        EntryListView.as_view(),
        name="entry_list",
    ),
    path(
        "entries/create/",
        EntryCreateView.as_view(),
        name="entry_create",
    ),
    path(
        "entries/update/<slug>",
        EntryUpdateView.as_view(),
        name="entry_update",
    ),
    path(
        "entries/delete/<slug>",
        EntryDeleteView.as_view(),
        name="entry_delete",
    ),
    path(
        "moods/",
        MoodListView.as_view(),
        name="mood_list",
    ),
    path(
        "moods/create/",
        MoodCreateView.as_view(),
        name="mood_create",
    ),
    path(
        "moods/update/<slug>",
        MoodUpdateView.as_view(),
        name="mood_update",
    ),
    path(
        "moods/reorder/",
        MoodReorderView.as_view(),
        name="mood_reorder",
    ),
    path(
        "moods/delete/<slug>",
        MoodDeleteView.as_view(),
        name="mood_delete",
    ),
    path(
        "activities/",
        ActivityListView.as_view(),
        name="activity_list",
    ),
    path(
        "activities/create/",
        ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activities/update/<slug>",
        ActivityUpdateView.as_view(),
        name="activity_update",
    ),
    path(
        "activities/delete/<slug>",
        ActivityDeleteView.as_view(),
        name="activity_delete",
    ),
]
