FEELINGS_LIST = [
    "Happy",
    "Sad",
    "Angry",
    "Excited",
    "Anxious",
    "Content",
    "Depressed",
    "Euphoric",
    "Grateful",
    "Guilty",
    "Lonely",
    "Loved",
    "Melancholy",
    "Optimistic",
    "Proud",
    "Relaxed",
    "Stressed",
    "Surprised",
    "Tired",
    "Confused",
]

ACTIVITY_LIST = [
    "Meditation",
    "Read a book",
    "Dance",
    "Gratitude journal",
    "Volunteer",
    "Movie marathon",
    "Power nap",
    "Journaling",
    "Listen to a podcast",
    "Neighborhood walk",
    "Watch a movie",
    "Bike ride",
    "DIY project",
    "Workout class",
    "Game night",
    "Hiking trail",
    "Attend a workshop",
]
